version: "3"
services:
  dbserver:
      image: mysql:5.7.13
      environment:
        - MYSQL_ROOT_PASSWORD=ap0ll0
        - MYSQL_DATABASE=cyclos3
      ports:
        - "3306:3306"
  coreserver:
      image: smartbank/core-service
      ports:
       - "9090:8080"
      links:
       - dbserver


